---
# tasks file for myvhost

- name: Ensure httpd is installed
  become_user: root
  remote_user: ansible
  become: true
  ansible.builtin.dnf:
    name: httpd
    state: latest


- name: Ensure httpd is started and enabled
  become_user: root
  become: true
  remote_user: ansible
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true


- name: vhost file is installed
  become_user: root
  become: true
  remote_user: ansible
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
