---
- name: Verify the index.html file
  hosts: all

  tasks:

  - name: Verify the index.html file is in place
    ansible.builtin.command: cat /var/www/vhosts/ansible-awx/index.html
    register: content

  - name: What does the index.html config file contain
    ansible.builtin.debug:
      msg: '{{ content }}.stdout_lines'
